[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ignored_error_codes = ["license", "code-size", "unreachable"]
fs_permissions = [{ path = "./", access = "read" }]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
