[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ignored_error_codes = ["license", "code-size", "unreachable"]
fs_permissions = [{ path = "./", access = "read" }]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
